### ISSUE TITLE
MetaOutput window continues to report DirectX warnings after debuggee has been stopped.

### ISSUE THREAD

**Issue by MichaelKv** [viacheslav-lozinskyi/MetaOutput#9] opened 2021-11-29 23:14 UTC
Hello. When I debug a DearImGUI application and get a message from the DirectX subsystem then the MetaOutput gets stuck and the endless following messages appear:
D3D12 : ID3D12CommandList::DrawIndexedInstanced: Viewport: 0 is non-empty while the corresponding scissor rectangle is empty. Nothing will be written to the render target when this viewport is selected. In D3D12, scissor testing is always enabled. [ EXECUTION WARNING #695: DRAW_EMPTY_SCISSOR_RECTANGLE] @@@SOURCE DEBUG @@@TYPE WARNING

The time in the left corner of the Debug.Begin upper line ticks, “Program started” slider in the right corner runs but the program has been already stopped indeed and the standard VS Output window reads “The program XXX hax exited with code 0 (0x0.”
Closing or clearing MetaOutput window does not help and I need to restart the Visual Studio to continue to work. Starting a next debugging session does not help.
I do admit it may be a Visual Studio problem but I cannot tell for sure – I am DearImGUI and DirectX newbie.
P.S. The same messages appear in the standard Output window but they stop to appear when the debuggee is stopped.

**Comment by viacheslav-lozinskyi** [comment] 2021-11-30 08:12
Seems this problem appears because huge number of similar messages were added to output in short period of time.
MetaOutput in difference to standard output can perform nearby 2000 messages in second.
After exceeding of this limit, message queue is growing and reaction on new messages is postponed.

I can collapse similar messages to one line. It will solve the problem.

In any case, thank you for the reported bug.
It will be fixed in the next release.

**Comment by MichaelKv** [comment] 2021-11-30 08:37
If by collapsing to one line you mean the messages will reappear when I hit “expand” or something like that then I would rather prefer you just count them.
BTW, ImGUI shall not render the screen that often (it is 50 or 60 Hz). 2000 messages per second may appear if they are generated by many items. Anyway, it looks like they appear if I am in middle of implementation of a new graphic element and do something wrong. At least I hope so.
Thanks.

P.S. Please, reconsider the allowing of bigger text size functionality.

**Comment by viacheslav-lozinskyi** [comment] 2021-11-30 11:07
About collapsing - all similar messages which is going one by one, will be shown as one message with hit counter.
I already made this functionality today.

About font size - you are not first who ask about it.
I plan to take font size from IDE font settings.
Own font settings I will not make in any case.

I don't do it because in Visual Studio API to find where those settings isn't simple issue.
Now I have more priority tasks related with this project...

**Comment by MichaelKv** [comment] 2021-11-30 14:05
Please, take into account that my VS 2019 is running idle (no debugging or running debuggee another way) for almost an hour and the message as above has never stopped. The pace is one message per second (a little bit less indeed). Memory consumption is 550-600 Mb, total CPU utilization is 6% but 1 core is fully occupied.

**Comment by viacheslav-lozinskyi** [comment] 2021-11-30 14:18
For me is not clear where is a problem?

1. If memory consumption - that is not a problem, because it is growing together with collected data (MetaOutput consume relatively big amount of memory). To solve this problem is necessary to make deep refactoring of code. I am not ready to do it now.
2. If CPU utilization - could you ensure that this utilization related to MetaOutput? Any other extension of Visual Studio, or IDE can consume CPU. I very attentively care about performance issues, and all known for me problems were solved. At least nobody from users for previous year didn't report such issues. I didn't found any related problems too.

In any case. any additional information will be appreciated.

**Comment by viacheslav-lozinskyi** [comment] 2021-11-30 15:18
Will be great if you try to reproduce the problem in your full development environment without MetaOutput.
It will give exact answer about is MetaOutput has influence to this problem.

Also will be great if you capture the problem by this tool [ShareX](https://getsharex.com/) and attach captured video.
Thanks in advance.

**Comment by MichaelKv** [comment] 2021-12-02 00:20
ImGUI developers fixed the issue with DRAW_EMPTY_SCISSOR_RECTANGLE I reported them and the MetaOutput problem is gone for me. But until the fix the standard Output Window handled that messages bombing pretty good at the lowest possible 1.8 GHz, 1 core fully busy 20-25% (no core switching), > 80k messages, no lagging after the debuggee stop, etc.
So, if you want to investigate the problem you would probably emulate the messages with a test application. I do not think it will be of a great help for you but just for the sake of a formality: ImGUI fix is https://github.com/ocornut/imgui/commit/440824d4314b59049a196e9e6964d8e72aed25bd (so one need an earlier build to get DRAW_EMPTY_SCISSOR_RECTANGLE messages); and their Demo application generated only one message then it crashed so you probably do not want to waste time on it. But it is possible to make an ImGui application to generate endless real-life DRAW_EMPTY_SCISSOR_RECTANGLE indeed.

**Comment by viacheslav-lozinskyi** [comment] 2021-12-02 06:47
Thank you a lot for the investigation.
I already made necessary stability changes which will solve similar situation correctly.
It will be available in next release.

**Comment by viacheslav-lozinskyi** [comment] 2022-01-03 21:23
This functionality is released in MetaOutput 2.0.9.191.
It is already available for updating from Visual Studio Marketplace.
Please verify that the fix is working.

**Closed** 2022-01-04 12:09 UTC
Labels: bug
