### ISSUE TITLE
Option to change fonts?

### ISSUE THREAD

**Issue by marcLeb** [viacheslav-lozinskyi/MetaOutput#16] opened 2022-11-19 10:06 UTC
Hi, i would really appreciate a way to modify the font for MetaOutput. Take a look at this screenshot to see why:

![Screenshot 2022-11-19 110612](https://user-images.githubusercontent.com/84007877/202845581-13da69f9-5494-44fa-8b69-6820a1008522.jpg)

**Comment by viacheslav-lozinskyi** [comment] 2022-11-19 10:28
Hi, thank you for this bug report.

This is very serious bug and I will fix it ASAP.
However, I never saw such behaviuor before, and nobody reported similar problem.
Therfore I need your assistance in solving this problem.

I have question questions to you:
1. Could you write name and version of your Operating System, version of Visual Studio and version of MetaOutput?
2. Could you make video screen capture of this case by [ShareX](https://getsharex.com/) tool?

Thank you in advance.

**Comment by marcLeb** [comment] 2022-11-19 10:44
Maybe it is because I use MacType or replaced some default system fonts some time ago. Thats why an option would be nice.
Here you got the infos you asked for:

Video: [https://youtu.be/E_m-kDCI2H8](url)

OS:

![Screenshot 2022-11-19 113249](https://user-images.githubusercontent.com/84007877/202846780-c23068c2-491b-4695-9d91-3bdc8e1f8b19.jpg)

IDE:

![Screenshot 2022-11-19 113215](https://user-images.githubusercontent.com/84007877/202846786-6f34a46b-8148-40f2-8ea0-760690e42bd3.jpg)


MetaOutput:

![Screenshot 2022-11-19 113322](https://user-images.githubusercontent.com/84007877/202846812-58f7ee8a-4ea3-4262-9bbd-f5bd0f98826b.jpg)

**Comment by viacheslav-lozinskyi** [comment] 2022-11-19 10:49
Thank you a lot for this information.

I will make change font to that is used by Visual Studio editor.
It should solve the problem.

I will inform you when this bug will be fixed.

**Comment by marcLeb** [comment] 2022-11-19 12:06
Yeah that sounds like a reasonable fix.
Looking forward for your update 😊

**Comment by viacheslav-lozinskyi** [comment] 2022-12-04 10:26
Fixed in MetaOutput 1.1.1.195.
It is already released.
Зlease see if the problem is solved.

Thank you in advance.

**Comment by marcLeb** [comment] 2022-12-05 07:34
WOW, this is very nice, thanks for your great work😀 Now not only the bug is gone, it is also a very nice feature that MetaOutput now matches the other fonts used in Visual Studio.
Big thanks 👍

![Unbenannt](https://user-images.githubusercontent.com/84007877/205579470-29e7620a-ba9a-4305-8a93-34f4d95e6369.PNG)

**Comment by viacheslav-lozinskyi** [comment] 2022-12-05 10:46
Thank you for reported bug, and for appreciation of my work ;)

**Closed** 2022-12-05 10:47 UTC
Labels: bug

**Comment by Grosner300** [comment] 2023-09-24 14:36
Can you show where, in VS 2022, we can change the font setting that affects the MetaOutput window?

**Comment by viacheslav-lozinskyi** [comment] 2023-09-24 16:09
![image](https://github.com/viacheslav-lozinskyi/MetaOutput/assets/51988029/138c1e1f-3480-43ad-a07e-2edd3b137fa2)

Font name is the same as in "Output Window".
Font size in settings is ignored.

**Comment by Grosner300** [comment] 2023-09-25 23:21
The setting does change the font size for the VS 2022 Community Edition Output window, but does NOT change the font size for the MetaOutput window.  

Is there a another way to adjust the font size for the MetaOutput window? 

![2023_09_25_19_13_40_MetaOutput-Visual_Studio Community-2022](https://github.com/viacheslav-lozinskyi/MetaOutput/assets/24656399/0570d369-df12-4903-a430-17e7c72f33af)

**Comment by viacheslav-lozinskyi** [comment] 2023-09-26 06:41
Font size is not possible to change in actual version.
You can change only font name.
