### ISSUE TITLE
Application crash if the extension is enabled

### ISSUE THREAD

**Issue by 3uclide** [viacheslav-lozinskyi/MetaOutput#13] opened 2022-08-02 23:48 UTC
I've stumble on this extension yesterday and it seems great. 

My application crash at random location if the extension is enabled. As soon as I disable the extension I can launch/debug my application again. 
At first I though it was some new code I wrote, but after commenting/reverting the application would still crash. 

Any idea?

**Comment by viacheslav-lozinskyi** [comment] 2022-08-03 03:18
Thank you for bug reporting.

You first man who write about crashes related with MetaOutput, and it's look strange.
I don't argue that in this application can be critical error.
It's possible and I fixed such bugs many times earlier.
Strange situation that you see it.

The reason why you should not see any appearance of any bug in this extension in error handling mechanism of MetaOutput.
Absolutely all exceptions there are caught by try / catch mechanism, and when such events appear, exception information, stack trace, version of application and OS version is sending to me for fixing.
For user it looks like as some feature is not working (in worse case).
Not more.
Restart of Visual Studio recover the normal work.
Therefore, you physically can't see any appearance of such bug...

Moreover, I don't see any critical error reported by this mechanism.

In any case I am ready to accept that you really found critical bug, and I will fix it.
However, you as programmer, should know that your information is completely not enough for fixing.
If you want my fix, please provide next information:
- Visual Studio version;
- OS version;
- Screenshot with appearance of bug or captured video from screen by [ShareX](https://getsharex.com/);
- Steps to reproduce (with stable reproduce it should not be a problem);
- List of other installed extensions.

As you wrote, your bug has stable reproduce, and it's great because it's simpler to find and fix.
I am waiting additional information from you, and thank you in advance.

**Comment by viacheslav-lozinskyi** [comment] 2022-08-03 06:22
I read again your comment.
Seems it's crash not appears in MetaOutput, but in your application.

Only one thing in theory can have influence, it's MetaOutput debugging mechanism.
Hovewer it's activated when you stop application on breakpoint...

![image](https://user-images.githubusercontent.com/51988029/182537181-a49c5439-35e5-4ef8-a577-efca0ea4cf4f.png)

You can try to disable MetaOutput debugging mechanism by clicking on "Popup Menu / Settings/ Debugging / Enable debugging".

Please verify is it solve the problem.

**Comment by 3uclide** [comment] 2022-08-03 17:20
Disabling the debugging mechanism fixed the crashes. (At least I can use the extension now :D)

Some infos:
* Visual Studio version: VS 2022 -> 17.2.6
* OS version: Windows 10 Pro -> 10.0.19044 Build 19044
* Steps to reproduce (with stable reproduce it should not be a problem): I'll try to reproduce with a clean solution (my solution has around 30 projects) because I just press play and most of the time it crashes (After a fresh visual studio start its may work once) 
* List of other installed extensions: Markdown Editor V2, VAX, VSColorOutput64, IncludeToolBoxVS2022, Entrian Source Search 2022, Trailing Whitespace Visualizer

One of the crash: 
![image](https://user-images.githubusercontent.com/6691715/182667477-6a30f7ad-c082-4df0-8cdc-708257032a70.png)

**Comment by viacheslav-lozinskyi** [comment] 2022-08-03 18:07
This is useful clarification, thanks.

So, the problem is in MetaOutput debugging mechanism...
I will think about it.

Also, will be great to get clear project with stable reproduce of this bug.
It's part of solution.

Also, I need additional information:
- Is it happened when you stop on breakpoint, or without stops?
- Looking on screenshot exception appears after main application is stopped. Correct?
- Is this message "... 0xC0000139: Entry Point Not Found." duplicated in standard "Output Window"?
- Is it only one exception related with MetaOutput?

P.S.
Seems, fix of concrete this exception is described [here](https://stackoverflow.com/questions/49672036/deploy-uwp-on-release-error-0xc0000139-entry-point-not-found).

**Comment by 3uclide** [comment] 2022-08-03 18:53
I think I found the issue. 

I had some lld-link warning for a while. The fix was to upgrade from clang 13 to clang 14. Since it didn't cause any problems, I was waiting on Visual Studio to update the built-in version.

The warning were related to pdb and the problem seems to be debugging related so I downloaded clang 14 and compiled my application with it. 

It now works perfectly fine.

Some infos about the warnings:
https://developercommunity.visualstudio.com/t/lots-of-lld-link-warnings-about-pdb-with-vs2022-17/1667797

As for your questions:
* The crash happened on boot, sometimes putting a breakpoint would prevent the crash, sometimes it would not.
* The application could not start
* It was in the standard "Output Window"
* I'm not sure what you mean by that

**Comment by viacheslav-lozinskyi** [comment] 2022-08-03 19:10
As I understand the problem is solved, and it's not related to MetaOutput.
Correct?

**Comment by 3uclide** [comment] 2022-08-03 19:56
The problem is solved on my side. 

From what I understand its an issue with deterministic build where the GUID is not generated properly for pdb. That exposed a bug in Clang 13 which they fixed in Clang 14. 

I don't know if you can somehow prevent the crash that I had because without the MetaOutput debugging activated I never have that crash. Maybe you're fed bad datas by Visual Studio and can't do anything.

**Comment by viacheslav-lozinskyi** [comment] 2022-08-03 20:20
I glad that this problem is solved, and it’s not in my code.

I think the problem should be solved in Clang (where it’s already solved).
Better I will spend my time on improvement of this product…

So, I will close this bug.

**Closed** 2022-08-03 20:21 UTC
Labels: bug, question
